---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-backend
  namespace: production
  annotations:
    iam.gke.io/gcp-service-account: suidex-backend@PROJECT_ID.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@PROJECT_ID.iam.gserviceaccount.com
